### ISSUE TITLE
Cheat Sheet

### ISSUE THREAD

**Issue by kekoziar** [kekoziar/python-novice-inflammation#3]
Add PDF/print friendly cheat sheet to the repository

**Comment by ngeraci** [comment]
added with commit https://github.com/kekoziar/python-novice-inflammation/commit/c689aaa62b4ded2d140fdefc223f29044dce9fee. google doc is [here](https://docs.google.com/document/d/1su63FgX2fWHtMFp01NvqYAXwZ_FcgzmocI_C5Hia1gs/edit?usp=sharing) if we need to make changes to the PDF.
